### ISSUE TITLE
Does not create md5 string

### ISSUE THREAD

**Issue by siddharth-paneri** [soffes/Crypto#29]
I guess the issue is in **Data+Crypto** file
I had to write 0 in place of index while interating thorugh pointer
`var hex: String {
		var string = ""
		enumerateBytes { pointer, index, _ in
			for i in index..<pointer.count {
				string += String(format: "%02x", pointer[i])
			}
		}
		return string
	}`

**Comment by soffes** [comment]
Which version of Swift are you on? I recently changed this to make it work in Swift 3.1

**Comment by ghost** [comment]
I had a similar issue and replacing index with 0 worked for me.

The difference though is that I'm using Swift 3.0.2 which is another problem because I can't install Crypto via Carthage since 0.5.1 requires 3.0.1 and 0.52 requires Swift 3.1.
I ended up installing CommonCrypto and manually adding the files from your library to my project.

I don't expect a fix to my specific issue since I can easily move to 3.1 and use the latest version of your library and for now I'm doing just a spike.

Nice work btw :)

**Comment by soffes** [comment]
Does a86569707ea7fa460fa4ad75a7195824074d259f work for you?

**Comment by siddharth-paneri** [comment]
Yes works for me. Although I did not check in Swift  3.1 yet.

**Comment by ghost** [comment]
Yeah, a865697 works for me too. Thank you.
